---
editor_options:
  chunk_output_type: console
---

```{r setup}
loadNamespace("httr")
loadNamespace("tidyverse")
loadNamespace("googlesheets4")
```

```{r get_history}
main_league_history_neat <- 
  httr::content(httr::GET(
    url = "https://lm-api-reads.fantasy.espn.com/apis/v3/games/ffl/leagueHistory/437568?view=kona_history_standings"
  ))

main_league_historical_standings_initial <- 
  sapply(1:length(main_league_history_neat), function (x) {
    
    fantasy_year_x <- main_league_history_neat[[x]]$seasonId
    
    season_metrics_x <- 
      sapply(1:length(main_league_history_neat[[x]]$teams), function (y) {
        
        team_name_y <- main_league_history_neat[[x]]$teams[[y]]$name
        
        team_owner_id_y <- main_league_history_neat[[x]]$teams[[y]]$owners[[1]]
        
        season_standing_y <- main_league_history_neat[[x]]$teams[[y]]$rankCalculatedFinal
        
        wins_y <- main_league_history_neat[[x]]$teams[[y]]$record$overall$wins
        
        losses_y <- main_league_history_neat[[x]]$teams[[y]]$record$overall$losses
        
        ties_y <- main_league_history_neat[[x]]$teams[[y]]$record$overall$ties
        
        percentage_y <- main_league_history_neat[[x]]$teams[[y]]$record$overall$percentage
        
        data.frame(
          team_name = team_name_y,
          team_owner_id = team_owner_id_y,
          season_standing = season_standing_y,
          wins = wins_y,
          losses = losses_y,
          ties = ties_y,
          percentage = percentage_y
        )
        
        }, simplify = FALSE) |> 
      dplyr::bind_rows()
    
    season_metrics_x |> 
      dplyr::mutate(
        fantasy_year = fantasy_year_x
      )
    
  }, simplify = FALSE) |> 
  dplyr::bind_rows() |> 
  dplyr::mutate(
    league = "Possum Track Pigskins"
  )

auction_league_history_neat <- 
  httr::content(httr::GET(
    url = "https://lm-api-reads.fantasy.espn.com/apis/v3/games/ffl/leagueHistory/963906?view=kona_history_standings"
  ))

auction_league_historical_standings_initial <- 
  sapply(1:length(auction_league_history_neat), function (x) {
    
    fantasy_year_x <- auction_league_history_neat[[x]]$seasonId
    
    season_metrics_x <- 
      sapply(1:length(auction_league_history_neat[[x]]$teams), function (y) {
        
        team_name_y <- auction_league_history_neat[[x]]$teams[[y]]$name
        
        team_owner_id_y <- auction_league_history_neat[[x]]$teams[[y]]$owners[[1]]
        
        season_standing_y <- auction_league_history_neat[[x]]$teams[[y]]$rankCalculatedFinal
        
        wins_y <- auction_league_history_neat[[x]]$teams[[y]]$record$overall$wins
        
        losses_y <- auction_league_history_neat[[x]]$teams[[y]]$record$overall$losses
        
        ties_y <- auction_league_history_neat[[x]]$teams[[y]]$record$overall$ties
        
        percentage_y <- auction_league_history_neat[[x]]$teams[[y]]$record$overall$percentage
        
        data.frame(
          team_name = team_name_y,
          team_owner_id = team_owner_id_y,
          season_standing = season_standing_y,
          wins = wins_y,
          losses = losses_y,
          ties = ties_y,
          percentage = percentage_y
        )
        
        }, simplify = FALSE) |> 
      dplyr::bind_rows()
    
    season_metrics_x |> 
      dplyr::mutate(
        fantasy_year = fantasy_year_x
      )
    
  }, simplify = FALSE) |> 
  dplyr::bind_rows() |> 
  dplyr::mutate(
    league = "Sunday Funday"
  )
```

```{r clean_up}
main_league_historical_standings_final <- 
  main_league_historical_standings_initial |> 
  dplyr::mutate(
    person = dplyr::case_when(
      team_owner_id %in% c("{29D7E39A-BEC2-4E20-8D70-ABB906894D16}") ~ "Granddaddy",
      team_owner_id %in% c("{8639A4D6-CA58-4724-99C6-92F5DE4DF473}") ~ "Tommy",
      team_owner_id %in% c("{445EDBE6-4125-4E63-9D9F-4C48BD91B585}") ~ "Mike",
      team_owner_id %in% c("{4740FEA4-B1BE-408F-91AB-C1BBC92EC9A0}") ~ "Tracy",
      team_owner_id %in% c("{E8B83555-3FD1-48C2-A3AE-B3CC87ED3212}") ~ "JD",
      team_owner_id %in% c("{2621F953-1936-4FA5-823E-1CEC0F305205}", "{BD49D75C-78CD-4941-91D0-0CF026FD1881}") ~ "Katie",
      team_owner_id %in% c("{23182676-C0BC-41AB-B5BB-0FF0DA5BC2FB}") ~ "Daniel",
      team_owner_id %in% c("{62D8A5A9-AF50-494C-B1B6-082C32F719D4}", "{8B152243-EA74-4681-9AB6-58CFC98A7779}") ~ "Jason",
      team_owner_id %in% c("{57531954-5897-448F-A481-7CBFD6A6BF52}", "{AFE1AE40-B461-4FDA-A7C8-E888DC5B2215}") ~ "Cyndi",
      team_owner_id %in% c("{E6543FB6-B99C-4E5C-95F2-CC40D2268A19}") ~ "Paul",
      team_owner_id %in% c("{F8A0F4C9-FEA4-4E81-A0F4-C9FEA41E81C5}") ~ "Brynna",
      team_owner_id %in% c("{E291F6A3-9CD4-4ACD-B35A-C0BB3E6FEE1D}", "{6347287C-EAE1-4D07-8DDF-E31A63253A25}") ~ "Nick",
      team_owner_id %in% c("{FF9C5795-66C8-4E60-9C57-9566C86E6011}") ~ "Anna",
      team_owner_id %in% c("{4DB3878D-694E-43D9-9A37-30DDDA9C2D74}") ~ "Eddie",
      team_owner_id %in% c("{46921C2C-910A-4EE2-921C-2C910ADEE245}") ~ "Nikki",
      team_owner_id %in% c("{4CF9F045-3A8A-4BFC-9543-3CF5FED37221}") ~ "Patrick",
      team_owner_id %in% c("{FE5774F6-D319-4236-B048-CF69D25AB276}") ~ "Bud",
      team_owner_id %in% c("{B5E78402-6C7E-4A28-93EB-7A4C201E4E1B}") ~ "Jeb",
      team_owner_id %in% c("{B541AE42-A991-4BD1-AA2A-311791D5E357}") ~ "Luke",
      team_owner_id %in% c("{5EFA6D4C-9A14-49DD-B5B4-68D18F181F12}") ~ "Mikey",
      TRUE ~ "unknown"
    )
  )

main_league_historical_standings_final |> 
  dplyr::filter(person %in% "unknown") |> 
  dplyr::count(team_owner_id, team_name)

auction_league_historical_standings_final <- 
  auction_league_historical_standings_initial |> 
  dplyr::mutate(
    person = dplyr::case_when(
      team_owner_id %in% c("{29D7E39A-BEC2-4E20-8D70-ABB906894D16}") ~ "Granddaddy",
      team_owner_id %in% c("{8639A4D6-CA58-4724-99C6-92F5DE4DF473}") ~ "Tommy",
      team_owner_id %in% c("{445EDBE6-4125-4E63-9D9F-4C48BD91B585}") ~ "Mike",
      team_owner_id %in% c("{4740FEA4-B1BE-408F-91AB-C1BBC92EC9A0}") ~ "Tracy",
      team_owner_id %in% c("{E8B83555-3FD1-48C2-A3AE-B3CC87ED3212}") ~ "JD",
      team_owner_id %in% c("{2621F953-1936-4FA5-823E-1CEC0F305205}", "{BD49D75C-78CD-4941-91D0-0CF026FD1881}") ~ "Katie",
      team_owner_id %in% c("{23182676-C0BC-41AB-B5BB-0FF0DA5BC2FB}") ~ "Daniel",
      team_owner_id %in% c("{62D8A5A9-AF50-494C-B1B6-082C32F719D4}", "{8B152243-EA74-4681-9AB6-58CFC98A7779}") ~ "Jason",
      team_owner_id %in% c("{57531954-5897-448F-A481-7CBFD6A6BF52}", "{AFE1AE40-B461-4FDA-A7C8-E888DC5B2215}") ~ "Cyndi",
      team_owner_id %in% c("{E6543FB6-B99C-4E5C-95F2-CC40D2268A19}") ~ "Paul",
      team_owner_id %in% c("{F8A0F4C9-FEA4-4E81-A0F4-C9FEA41E81C5}") ~ "Brynna",
      team_owner_id %in% c("{E291F6A3-9CD4-4ACD-B35A-C0BB3E6FEE1D}", "{6347287C-EAE1-4D07-8DDF-E31A63253A25}") ~ "Nick",
      team_owner_id %in% c("{FF9C5795-66C8-4E60-9C57-9566C86E6011}") ~ "Anna",
      team_owner_id %in% c("{4DB3878D-694E-43D9-9A37-30DDDA9C2D74}") ~ "Eddie",
      team_owner_id %in% c("{46921C2C-910A-4EE2-921C-2C910ADEE245}") ~ "Nikki",
      team_owner_id %in% c("{4CF9F045-3A8A-4BFC-9543-3CF5FED37221}") ~ "Patrick",
      team_owner_id %in% c("{FE5774F6-D319-4236-B048-CF69D25AB276}") ~ "Bud",
      team_owner_id %in% c("{B5E78402-6C7E-4A28-93EB-7A4C201E4E1B}") ~ "Jeb",
      team_owner_id %in% c("{B541AE42-A991-4BD1-AA2A-311791D5E357}") ~ "Luke",
      team_owner_id %in% c("{5EFA6D4C-9A14-49DD-B5B4-68D18F181F12}") ~ "Mikey",
      TRUE ~ "unknown"
    )
  )

auction_league_historical_standings_final |> 
  dplyr::filter(person %in% "unknown") |> 
  dplyr::count(team_owner_id, team_name)

historical_standings_final <- 
  dplyr::bind_rows(main_league_historical_standings_final, auction_league_historical_standings_final)
```

```{r summaries}
main_leauge_historical_standings_summary <- 
  main_league_historical_standings_final |> 
  dplyr::group_by(person) |> 
  dplyr::summarize(
    overall_percentage_median = stats::median(percentage)
  ) |> 
  dplyr::ungroup() |> 
  dplyr::arrange(dplyr::desc(overall_percentage_median))

auction_leauge_historical_standings_summary <- 
  auction_league_historical_standings_final |> 
  dplyr::group_by(person) |> 
  dplyr::summarize(
    overall_percentage_median = stats::median(percentage)
  ) |> 
  dplyr::ungroup() |> 
  dplyr::arrange(dplyr::desc(overall_percentage_median))

historical_standings_summary <- 
  historical_standings_final |> 
  dplyr::mutate(
    percentage = round(percentage, 4)
  ) |> 
  dplyr::group_by(person) |> 
  dplyr::summarize(
    percentage_median = stats::median(percentage),
    percentage_mean = mean(percentage),
    seasons_played = dplyr::n()
  ) |> 
  dplyr::ungroup() |> 
  dplyr::mutate(
    overall_percentage = percentage_median + percentage_mean
  ) |> 
  dplyr::arrange(dplyr::desc(overall_percentage))
```

```{r upload_google}
google_sheet <- "https://docs.google.com/spreadsheets/d/1kGHhWmJMOuvvL-9YY-lRBoZ7iCjmNCFU6VR3_vmVyk4"

historical_standings_final |> 
  dplyr::select(person, dplyr::everything(), -team_owner_id) |> 
  dplyr::mutate(
    percentage = round(percentage, 4)
  ) |> 
  googlesheets4::write_sheet(
    ss = google_sheet,
    sheet = "data_neat"
  )

historical_standings_summary |> 
  googlesheets4::write_sheet(
    ss = google_sheet,
    sheet = "JB_summary"
  )
```

```{r visuals}
historical_standings_final |> 
  dplyr::group_by(person) |> 
  dplyr::summarize(
    total_wins = sum(wins),
    total_losses = sum(losses)
  ) |> 
  dplyr::ungroup() |> 
  
  ggplot2::ggplot(ggplot2::aes(forcats::fct_infreq(person, total_wins))) +
  ggplot2::geom_bar(
    ggplot2::aes(
      y = total_wins
    ), 
    stat = "identity",
    fill = "#cccccc"
  ) + 
  ggplot2::geom_text(
    ggplot2::aes(
      label = total_wins,
      y = total_wins + max(total_wins)*0.03,
    ),
    size = 4
  ) +
  ggplot2::labs(
    title = "All Family Leagues' Winnings",
    x = "Owner",
    y = "Game Wins"
  ) +
  ggplot2::theme(
    title = ggplot2::element_text(size = 17),
    axis.title = ggplot2::element_text(hjust = 1, size = 15),
    axis.text.x = ggplot2::element_text(angle = 45, hjust = 1, vjust = 1, size = 13),
    axis.text.y = ggplot2::element_blank(),
    axis.ticks = ggplot2::element_blank(),
    panel.grid = ggplot2::element_blank(),
    panel.background = ggplot2::element_blank(),
    legend.position = "bottom",
    legend.text = ggplot2::element_text(size = 13)
  )

historical_standings_final |> 
  dplyr::group_by(person, league) |> 
  dplyr::summarize(
    total_wins = sum(wins),
    total_losses = sum(losses)
  ) |> 
  dplyr::ungroup() |>
  
  ggplot2::ggplot(ggplot2::aes(forcats::fct_infreq(person, total_wins))) +
  ggplot2::geom_bar(
    ggplot2::aes(
      y = total_wins,
      fill = league
    ), 
    position = "dodge",
    stat = "identity"
  ) + 
  ggplot2::geom_text(
    ggplot2::aes(
      label = total_wins,
      y = total_wins + max(total_wins)*0.03,
      group = league
    ),
    position = ggplot2::position_dodge(width = 0.9),
    size = 4
  ) +
  ggplot2::labs(
    title = "All Family Leagues' Winnings",
    x = "Owner",
    y = "Game Wins",
    fill = "League"
  ) +
  ggplot2::theme(
    title = ggplot2::element_text(size = 17),
    axis.title = ggplot2::element_text(hjust = 1, size = 15),
    axis.text.x = ggplot2::element_text(angle = 45, hjust = 1, vjust = 1, size = 13),
    axis.text.y = ggplot2::element_blank(),
    axis.ticks = ggplot2::element_blank(),
    panel.grid = ggplot2::element_blank(),
    panel.background = ggplot2::element_blank(),
    legend.position = "bottom",
    legend.text = ggplot2::element_text(size = 13)
  )

historical_standings_final |> 
  dplyr::group_by(person) |> 
  dplyr::summarize(
    total_wins = sum(wins),
    total_losses = sum(losses)
  ) |> 
  dplyr::ungroup() |> 
  tidyr::pivot_longer(
    cols = c(total_wins, total_losses),
    names_to = "category",
    values_to = "games"
  ) |> 
  dplyr::mutate(
    category = stringr::str_remove_all(category, "(^)total_")
  ) |> 
  dplyr::mutate(
    category = dplyr::case_when(
      category == "wins" ~ " wins",
      TRUE ~ category
    )
  ) |> 
  
  ggplot2::ggplot(ggplot2::aes(forcats::fct_infreq(person, games))) +
  ggplot2::geom_bar(
    ggplot2::aes(
      y = games,
      fill = category
    ), 
    position = "dodge",
    stat = "identity"
  ) + 
  ggplot2::geom_text(
    ggplot2::aes(
      label = games,
      y = games + max(games)*0.03,
      group = category
    ),
    position = ggplot2::position_dodge(width = 0.9),
    size = 4
  ) +
  ggplot2::labs(
    title = "All Family Leagues' Games",
    subtitle = "ordered by total games played",
    x = "Owner",
    y = "Games",
    fill = ""
  ) +
  ggplot2::theme(
    plot.title = ggplot2::element_text(size = 17),
    plot.subtitle = ggplot2::element_text(size = 15, face = "italic"),
    axis.title = ggplot2::element_text(hjust = 1, size = 15),
    axis.text.x = ggplot2::element_text(angle = 45, hjust = 1, vjust = 1, size = 13),
    axis.text.y = ggplot2::element_blank(),
    axis.ticks = ggplot2::element_blank(),
    panel.grid = ggplot2::element_blank(),
    panel.background = ggplot2::element_blank(),
    legend.position = "bottom",
    legend.text = ggplot2::element_text(size = 13)
  )

historical_standings_final |> 
  dplyr::group_by(person) |> 
  dplyr::summarize(
    percentage_median = stats::median(percentage)
  ) |> 
  dplyr::ungroup() |> 
  
  ggplot2::ggplot(ggplot2::aes(forcats::fct_infreq(person, percentage_median))) +
  ggplot2::geom_bar(
    ggplot2::aes(
      y = percentage_median
    ), 
    stat = "identity",
    fill = "#cccccc"
  ) + 
  ggplot2::geom_text(
    ggplot2::aes(
      label = round(percentage_median, 2)*100,
      y = percentage_median + max(percentage_median)*0.03,
    ),
    size = 4
  ) +
  ggplot2::labs(
    title = "All Family Leagues' Winnings",
    subtitle = "ties count as half wins",
    x = "Owner",
    y = "Median Win (%)"
  ) +
  ggplot2::theme(
    plot.title = ggplot2::element_text(size = 17),
    plot.subtitle = ggplot2::element_text(size = 15, face = "italic"),
    axis.title = ggplot2::element_text(hjust = 1, size = 15),
    axis.text.x = ggplot2::element_text(angle = 45, hjust = 1, vjust = 1, size = 13),
    axis.text.y = ggplot2::element_blank(),
    axis.ticks = ggplot2::element_blank(),
    panel.grid = ggplot2::element_blank(),
    panel.background = ggplot2::element_blank(),
    legend.position = "bottom",
    legend.text = ggplot2::element_text(size = 13)
  )
```
